Models/DonationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using System.Data.SqlClient;
using HSNHospitalProject.Models;
using HSNHospitalProject.Models.ViewModels;
using Stripe;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PagedList;

namespace HSNHospitalProject.Models
{
    public class DonationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Donation
        public ActionResult Index(int? page)
        {
            //Check if the user has the permission (admin)
            if (!IsAdmin())
            {
                //redirect to the home page
                return RedirectToAction("Create");
            }

            List<Donation> donations = db.Donations.ToList();
            List<DonationIndexViewModel> viewDonation = new List<DonationIndexViewModel>();
            for (int i = 0; i < donations.Count; i++)
            {
                viewDonation.Add(new DonationIndexViewModel(donations[i]));
            }
            //the amount of donations per page
            int pageSize = 10;
            //set the page number to 1 if it is not already set
            int pageNumber = (page ?? 1);
            return View(viewDonation.ToPagedList(pageNumber, pageSize));
        }

        // GET: Donation/Details/8
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Debug Purpose to see if we are getting the id
            Debug.WriteLine("I'm pulling data of " + id.ToString());

            //Get the specific Donation
            Donation donation = db.Donations.Find(id);

            //Could not find the specific Donation
            if (donation == null)
            {
                return HttpNotFound();
            }

            //return the Donation data 
            return View(donation);
        }

        // GET: Donation/Create
        public ActionResult Create()
        {
            return View();
        }

        //When user submits the form to add a new Donation
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DonationCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Debug Purpose to see if we are getting the data
                Debug.WriteLine("I'm pulling data of Name: " + model.name + ", Amount: " + model.amount + ", Email: " + model.email
                    + ", Anonymous: " + model.anonymous);
                    //+ ", Card Number: " + model.number + " Card ExpMonth: " + model.expMonth
                    //+ " Card ExpYear: " + model.expYear + " Card CVC: " + model.cvc);

                Donation newDonation = new Donation();
                newDonation.donationName = model.name;
                //Convert the Dollar CAD value to Cents value
                newDonation.donationAmount = (int)(model.amount * 100);
                newDonation.donationEmail = model.email;
                newDonation.donationAnonymous = model.anonymous;

                //This method is when you want the payment done on the Server Side (not safe due to sending card info.)
                /*
                StripeConfiguration.ApiKey = "sk_test_T3BF2ap8TTDpmetCKxF038r400HAf7zrj8";
                var options = new PaymentIntentCreateOptions
                {
                    Amount = model.amount,
                    Currency = "cad",
                    // Verify your integration in this guide by including this parameter
                    Metadata = new Dictionary<string, string>
                    {
                      { "integration_check", "accept_a_payment" },
                    }
                };

                var service = new PaymentIntentService();
                try
                {
                    var paymentIntent = service.Create(options);

                    //Create the Payment Method
                    PaymentMethodCreateOptions payMethodOptions = new PaymentMethodCreateOptions
                    {
                        Type = "card",
                        Card = new PaymentMethodCardCreateOptions
                        {
                            Number = model.number,
                            ExpMonth = model.expMonth,
                            ExpYear = model.expYear,
                            Cvc = model.cvc,
                        },
                        BillingDetails = new BillingDetailsOptions
                        {
                            Name = model.name
                        }
                    };

                    //Confirm the payment we are making
                    PaymentMethodService payMethodService = new PaymentMethodService();
                    PaymentMethod payMethod = payMethodService.Create(payMethodOptions);
                    PaymentIntentConfirmOptions payOptions = new PaymentIntentConfirmOptions
                    {
                        PaymentMethod = payMethod.Id
                    };
                    service = new PaymentIntentService();
                    service.Confirm(
                      paymentIntent.Id,
                      payOptions
                    );

                    //Add the id for the payment in the Stripe API (Unique identifier for the object)
                    newDonation.donationReceiptId = paymentIntent.Id;
                }
                catch (Exception e) {
                    Debug.WriteLine(e.Message);
                    //Something failed, redisplay form
                    return View(model);
                }
                */

                //Add the object to the database
                db.Donations.Add(newDonation);

                //Save the changes in the database
                db.SaveChanges();

                //Must confirm the payment
                return RedirectToAction("CardPayment/" + newDonation.donationId);
                
                //Go back to the list of Donation to see the added Donation (If everything is done in the Server Side)
                //return Redirect("List");
            }

            //Something failed, redisplay form
            return View(model);
        }

        // GET: Donation/CardPayment
        public ActionResult CardPayment(int? id)
        {
            if (id == null)
            {
                //change to redirect to 
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Debug Purpose to see if we are getting the id
            Debug.WriteLine("I'm pulling data of " + id.ToString());

            //Get the specific donation
            Donation donation = db.Donations.Find(id);

            //Could not find the specific donation
            if (donation == null)
            {
                return HttpNotFound();
            }

            StripeConfiguration.ApiKey = "sk_test_T3BF2ap8TTDpmetCKxF038r400HAf7zrj8";
            //Create a Payment Intent from Payment API
            PaymentIntentCreateOptions options = new PaymentIntentCreateOptions
            {
                Amount = donation.donationAmount,
                Currency = "cad",
                // Verify your integration in this guide by including this parameter
                Metadata = new Dictionary<string, string>
                {
                    { "integration_check", "accept_a_payment" },
                }
            };

            PaymentIntentService service = new PaymentIntentService();
            PaymentIntent paymentIntent = new PaymentIntent();

            //Loop is for trying to connect using the service (may fail, so try again)
            int retry = 0;
            for (int i = 0; i < 3; i++)
            {
                try
                {
                    paymentIntent = service.Create(options);
                    break;
                }
                catch (Exception e)
                {
                    retry++;
                }
            }
            //We failed 3 times, so return to the index page of the donation
            if (retry == 3) {
                //Delete the Donation from the table
                db.Donations.Remove(donation);

                //Save the changes on the database
                db.SaveChanges();

                //Go back to the list of Donation
                return RedirectToAction("Index");
            }

            ViewData["id"] = id;
            ViewData["clientSecret"] = paymentIntent.ClientSecret;
            ViewData["clientName"] = db.Donations.Find(id).donationName;

            //Add the id for the payment in the Stripe API (Unique identifier for the object)
            db.Donations.Find(id).donationReceiptId = paymentIntent.Id;

            //Save the changes in the database
            db.SaveChanges();

            return View();
        }

        //When user submits the form of the card info. and was successful
        [HttpPost]
        public ActionResult CardPayment() {
            //Go back to see the added Donation

            //Go back to the list of Donation if user is admin            
            if (IsAdmin())
            {
                return RedirectToAction("Index", new { add = true });
            }
            //Not a admin, so show message in the Create Page
            return RedirectToAction("Create", new { add = true });
        }

        //When user wants to cancel the payment
        public ActionResult CancelPayment(int id) {
            StripeConfiguration.ApiKey = "sk_test_T3BF2ap8TTDpmetCKxF038r400HAf7zrj8";

            Donation removedDonation = db.Donations.Find(id);

            //Cancel the Payment
            var service = new PaymentIntentService();

Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using System.Data.SqlClient;
using HSNHospitalProject.Helpers;
using HSNHospitalProject.Models;
using HSNHospitalProject.Models.ViewModels;

namespace HSNHospitalProject.Controllers
{
    public class ArticleController:Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();



        /// <summary>
        /// List Method for Article's returns a list of articles depending on the search string and page number
        /// </summary>
        /// <param name="articleSearchKey">The Search string entered in hte search input box in the view</param>
        /// <param name="pagenum"> the page which has to be displayed</param>
        /// <returns>Returns a List of Articles to the View.</returns>
        public ActionResult Index(string articleSearchKey,int pagenum=0)
        {
            
            //pass a value to the view without using a view model
            //here we can send a boolean which is used in the view to display create/update buttons and links if the user is an admin
            TempData["isAdmin"] = LoggedInChecker.isAdmin();

            //using Christine Bittle's method for pagination from PetGroomingMVC
            //https://github.com/christinebittle/PetGroomingMVC/blob/master/PetGrooming/Controllers/GroomServiceController.cs
            List<Article> articles = db.Articles.Where(a => (articleSearchKey != null) ? a.articleTitle.Contains(articleSearchKey) : true).ToList();
            int perpage = 3;
            int articleCount = articles.Count();
            int maxpage = (int)Math.Ceiling((decimal)articleCount / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = (int)(perpage * pagenum);
            ViewData["pagenum"] = pagenum;
            ViewData["pagesummary"] = "";
            if (maxpage > 0)
            {
                ViewData["pagesummary"] = (pagenum + 1) + " of " + (maxpage + 1);
                articles = db.Articles
                    .Where(a => (articleSearchKey != null) ? a.articleTitle.Contains(articleSearchKey) : true)
                    .OrderBy(a => a.articleId)
                    .Skip(start)
                    .Take(perpage)
                    .ToList();
            }

            

            return View(articles);
        }


        /// <summary>
        /// Create method for Articles, checks if the current user is an admin and allows access to ../Article/Create otherwise returns users to the List page
        /// </summary>
        /// <returns>Returns the Create View if the current user is an admin</returns>
        public ActionResult Create()
        {
            //using the helper method  to check if the current user is an admin
            if (LoggedInChecker.isAdmin())
            {
                return View();
            }
            else
            {//if they are not they are sent back to the list of articles
                return RedirectToAction("Index");
            }
            
        }


        /// <summary>
        /// Update method for articles, checks if the current user is an admin and allows access to ../Article/Update/id otherwise returns users to the List page 
        /// </summary>
        /// <param name="id">The is the id of the article which is to be updated</param>
        /// <returns>Returns the view containing the article who matches the id param</returns>
        public ActionResult Update(int? id)
        {
            //using the helper method  to check if the current user is an admin
            if (LoggedInChecker.isAdmin())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Article article = db.Articles.SqlQuery("select * from articles where articleId=@articleId", new SqlParameter("@articleId", id)).FirstOrDefault();

                if (article == null)
                {
                    return HttpNotFound();

                }
                return View(article);
            }
            else
            {
                //if they are not they are sent back to the list of articles
                return RedirectToAction("Index");
            }
        }
            
        
        /// <summary>
        /// The POST update method for articles, grabs the variables from the view and uses parametezied queries to add the changes to the database
        /// </summary>
        /// <param name="article">The article returned from the view</param>
        /// <param name="id">The id of the article which is going to be updated. </param>
        /// <returns></returns>
        [HttpPost]
        //since the non-POST method checks if the user is an admin there is no need to check again. 
        public ActionResult Update(Article article, int id)
        {
            string query = "update articles set articleTitle = @articleTitle, articleBody = @articleBody,articleDateLastEdit = @articleDateLastEdit where articleId = @id";

            SqlParameter[] sqlparams = new SqlParameter[4];
            sqlparams[0] = new SqlParameter("@articleTitle", article.articleTitle);
            sqlparams[1] = new SqlParameter("@articleBody", article.articleBody);
            sqlparams[2] = new SqlParameter("@articleDateLastEdit", DateTime.Now);
            sqlparams[3] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(query, sqlparams);
            return RedirectToAction("Index");

        }

        /// <summary>
        /// The POST Create method for articles 
        /// </summary>
        /// <param name="article">contains the article values from the view</param>
        /// <returns></returns>
        [HttpPost]
        //since the non-POST method checks if the user is an admin there is no need to check again. 
        public ActionResult Create(Article article)
        {
            
            string query = "insert into articles (articleTitle,articleBody,articleDatePosted)" +
                "values (@articleTitle,@articleBody,@articleDatePosted)";
            SqlParameter[] sqlParameters = new SqlParameter[3];
            sqlParameters[0] = new SqlParameter("@articleTitle", article.articleTitle);
            sqlParameters[1] = new SqlParameter("@articleBody", article.articleBody);
            sqlParameters[2] = new SqlParameter("@articleDatePosted", DateTime.Now);
            

            db.Database.ExecuteSqlCommand(query, sqlParameters);

            return RedirectToAction("Index");
            
        }


        /// <summary>
        /// Delete Method for article, currently only used in the Update view.
        /// </summary>
        /// <param name="id">The id of the article to be deleted</param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            //Check if the current user is an admin. 
            if (LoggedInChecker.isAdmin())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Article article = db.Articles.Find(id);
                db.Articles.Remove(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {//if they are not return them to the list of articles
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
@*LOGO and Banner belongs to HSN sudbury*@
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="jumbotron jumbotron-main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-1 col-sm-offset-2">
                        <img class="img-responsive" style="max-height:150px;" src="~/Content/img/logo.png" />
                    </div>
                    <div class="col-lg-6">
                        <div class="row">
                            <h1>Health Science North</h1>
                            <div class="col-sm-5 col-sm-offset-3">
                                <h2 style="margin-top:0px;">Horizon Santé-Nord</h2>
                            </div>
                        </div>

                    </div>
                    @*Login/Logout links*@
                    <div class="col-xs-2 col-xs-offset-1">
                        @Html.Partial("_LoginPartial")
                    </div>
                    @*Fake search bar*@
                    <div class="col-md-3 col-md-pull-1">
                        <input style="box-shadow: 5px 7px #888888;" placeholder="Search..." class="form-control" />
                    </div>
                    @*Donate button the bg color is the same orange from the logo*@
                    <div class="col-xs-1 col-xs-offset-2">
                        <button name="donateBTN" style="background-color:#EF8326;" class="btn btn-lg">
                            @Html.ActionLink("Donate", "Index", "Donation")
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                @*Html.ActionLink("HSN Hospital", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li><a href="#">Patients and Vistors</a></li>
                    <li><a href="#">Programs and Services</a></li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("News", "Index", "Article")</li>
                    <li>@Html.ActionLink("Image Gallery", "Index", "GalleryImages")</li>
                    <li>@Html.ActionLink("Department", "Index", "Department")</li>
                    <li>@Html.ActionLink("Doctors", "List", "Doctors")</li>
                    <li>@Html.ActionLink("Appointments", "List", "Appointments")</li>
                    <li>@Html.ActionLink("Job Posts", "Index", "JobPost")</li>
                </ul>

            </div>
        </div>
    </div>
    <div class="sidebar">
        <ul class="">
            @*dummy sidebar used glyphicons provided by bootstrap*@
            <li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span><a href="#"> Hospital Map</a></li>
            <li><span class="glyphicon glyphicon-time" aria-hidden="true"></span><a href="#"> Visting Hours</a></li>
            <li><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><a href="#"> Emergency Dept.</a></li>
            <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span><a href="#"> Accessibility</a></li>
            <li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href="#"> Join Newsletter</a></li>
        </ul>
    </div>
  

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>

            <a href="#">Terms of Use</a> |
            <a href="#">Site Map</a> |
            <a href="#">Terms of Use</a> |
            <p>&copy; @DateTime.Now.Year - Humber HSNSudbury</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
  
</body>
</html>

Views/Shared/_ShowDeleteInfo.cshtml
@model HSNHospitalProject.Models.ActivityRecords

<div class="modal-body">
    <p>Are you sure you want to delete the record for @Model.activityrecorddate.ToString("dddd, dd MMMM yyyy")?</p>

</div>

<div class="modal-footer">
    <a href="@Url.Action("Delete", new { id = Model.activityrecordid})" class="btn btn-danger">Delete</a>

    <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
</div>

Views/Shared/_ShowImage.cshtml
@model HSNHospitalProject.Models.GalleryImages

<div class="modal-header">
    <h4 class="modal-title" id="exampleModalLongTitle">@Model.galleryimagetitle</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <!--<div style="width:50%; float:left;">-->
                <div>
                    <img class="" src="~/Content/GalleryImages/@Model.galleryimageref" style="width:100%; height:50vh; object-fit: scale-down;" alt="@Model.galleryimagealt" />
                </div>
            </div>
            <div class="col-lg-6">
                <div class="galleryDescription">
                    <!--<div style="width:50%; float:right; padding-left: 20px;">-->
                    <p>@Model.galleryimagedescription</p>
                    <p><small><em>Posted on @Model.galleryimagedate.ToLongDateString()</em></small></p>
                </div>
            </div>
        </div>
    </div>

</div>

<div class="modal-footer">
    @if (TempData["isAdmin"] != null && (bool)TempData["isAdmin"] == true) //if the tempdata is set and the user is an admin
    {
        <a href="@Url.Action("Edit", new { id = Model.galleryimageid})" class="btn btn-success">Edit</a>
        <a href="@Url.Action("Delete", new { id = Model.galleryimageid})" class="btn btn-danger">Delete</a>
    }
    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
</div>

Views/Shared/_StartGraph.cshtml
@model HSNHospitalProject.Helpers.GraphValueHolder
@using HSNHospitalProject.Helpers;

<h3>How Busy Are We Today?</h3>
<!--Below is the canvas the generateGraph method will be drawing to-->
<canvas id="graph"></canvas>
<script src="~/Scripts/GraphGenerator.js" type="text/javascript"></script>
<script>
    //change the width and height values in the last 2 paramaters to change the width and the height (set in px)
    generateGraph("@Model.canvasId", @Model.sundayVal, @Model.mondayVal, @Model.tuesdayVal, @Model.wednesdayVal, @Model.thursdayVal, @Model.fridayVal, @Model.saturdayVal, 300, 200);
    console.log("The graphScript div on the home page has been filled with the script from the _StartGraph partial view.");
    console.log("@Model.printValues()");
</script>
@if (LoggedInChecker.isAdmin())
{
<div class="admin-graph-selections">
    <a href="@Url.Action("Index","ActivityRecords")" class="btn btn-default btn-xs">Records List</a>
    <a href="@Url.Action("Create","ActivityRecords")" class="btn btn-default btn-xs">Add Record</a>
</div>
}
<!--Today's Activity: High/Average/Low-->